def show_menu():
    print("\n" + "=" * 40)
    print("     MENU QUẢN LÝ SINH VIÊN")
    print("=" * 40)
    print("1. Thêm sinh viên")
    print("2. Xem danh sách sinh viên")
    print("3. Sửa thông tin sinh viên")
    print("4. Xóa sinh viên")
    print("5. Tìm sinh viên theo tên")
    print("6. Sắp xếp sinh viên theo tên")
    print("7. Lưu danh sách sinh viên vào file")
    print("8. Tải danh sách sinh viên từ file")
    print("9. Cập nhật thông tin sinh viên")
    print("0. Thoát")
    print("=" * 40)